name: CI Tempo

permissions: {}

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: "sccache"

jobs:
  sanity-check:
    runs-on: depot-ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      # Checkout the repository
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # master
        with:
          toolchain: stable

      - uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2

      # Build and install forge and cast
      - name: Build and install Forge and Cast
        run: |
          cargo install --path ./crates/forge --profile dev --force --locked
          cargo install --path ./crates/cast --profile dev --force --locked

      - name: Run Tempo check on testnet
        env:
          TEMPO_RPC_URL: ${{ secrets.TEMPO_TESTNET_RPC_URL }}
          VERIFIER_URL: ${{ secrets.VERIFIER_URL }}
        run: |
          chmod +x ./.github/scripts/tempo-check.sh
          ./.github/scripts/tempo-check.sh

      - name: Run Tempo check on devnet
        env:
          TEMPO_RPC_URL: ${{ secrets.TEMPO_DEVNET_RPC_URL }}
        run: |
          chmod +x ./.github/scripts/tempo-check.sh
          ./.github/scripts/tempo-check.sh
