name: CI Tempo

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: "sccache"

permissions:
  contents: write   # This is the key step

jobs:
  sanity-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # master
        with:
          toolchain: stable

      - name: Configure Git to use GITHUB_TOKEN for GitHub
        env:
          TOKEN: ${{ secrets.FOUNDRY_TEMPO_RELEASE_PAT }}
        shell: bash
        run: |
          authenticated_url="https://${GITHUB_ACTOR}:${TOKEN}@github.com/"
          echo "$authenticated_url"
          git config --global url."$authenticated_url".insteadOf "ssh://git@github.com/"

      - uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2

      # Build and install forge and cast
      - name: Build and install Forge and Cast
        run: |
          cargo install --path ./crates/forge --profile dev --force --locked
          cargo install --path ./crates/cast --profile dev --force --locked

      - name: Run Tempo check
        env:
          TEMPO_TOKEN: ${{ secrets.FOUNDRY_TEMPO_RELEASE_PAT }}
        run: |
          chmod +x ./.github/scripts/tempo-check.sh
          ./.github/scripts/tempo-check.sh
